services:
  app:
    image: travel-agency:latest
    build:
      context: ./
      dockerfile: "Dockerfile"
    container_name: web-app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=test_travel_agency"

