# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.8'
networks:
  backend:
    name: demo
    driver: bridge
volumes:
  postgres_data:
    driver: local

services:
  app:
    image: travel-agency:latest
    build:
      context: ./
      dockerfile: "Dockerfile"
    container_name: web-app
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=test_travel_agency"

