spring:
  application:
    name: travel-agency

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_travel_agency
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always